name: documenso-test

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=Angelo2424$
      - POSTGRES_DB=documenso
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U documenso']
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - 54322:5432

  inbucket:
    image: inbucket/inbucket
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100

  documenso:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      inbucket:
        condition: service_started
    env_file:
      - ../../.env.example
    environment:
      - NEXTAUTH_SECRET=A3B5FCE41AA9F08029F0A9C078327C2981982BCC3DF212100D24A51FA0477E69
      - NEXT_PRIVATE_ENCRYPTION_KEY=x66eRVYj33wbqheoo5FNoCoEXXtqS38p/FoFI6906VQ=
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=9m3ksnN25Wi6DqbSCRdkFyUHhzT87exzdUByVzbTkXE=
      - NEXT_PRIVATE_DATABASE_URL=postgres://documenso:Angelo2424$@database:5432/documenso
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=postgres://documenso:Angelo2424$@database:5432/documenso
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=database
      - NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
      - NEXT_PRIVATE_SMTP_HOST=smtp-relay.brevo.com
      - NEXT_PRIVATE_SMTP_PORT=587
      - NEXT_PRIVATE_SMTP_USERNAME=7559dd001@smtp-brevo.com
      - NEXT_PRIVATE_SMTP_PASSWORD=JF7P908t3EgGSDax
      - NEXT_PRIVATE_SMTP_FROM_NAME="DML-KKC"
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=corp@dmlkkc.com
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/cert.p12
    ports:
      - 3000:3000
    volumes:
      - ../../apps/web/example/cert.p12:/opt/documenso/cert.p12
